version: '3'
services:

  web:
    image: nginx:1.15
    restart: always
    volumes:
      - ../:/var/www:delegated
      - ./local.web.default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - db
    ports:
      - 8000:80

  app:
    build:
      context: ../
      dockerfile: docker/local.app.Dockerfile
    restart: always
    volumes:
      - ../:/var/www:delegated
      - ./local.app.php.ini:/usr/local/etc/php/php.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
      - ~/.yarn/docker-cache/:/root/.yarn:cached
    depends_on:
      - db
    environment:
      - "COMPOSER_ALLOW_SUPERUSER=true"
      - "DBUS_SESSION_BUS_ADDRESS=/dev/null"
    ports:
      - 5757:5757

  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ../docker/local.db.schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 13306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
