version: '3'
services:

  app:
    build:
      context: ../
      dockerfile: docker/local.app.Dockerfile
    restart: always
    volumes:
      - ../:/var/www
      - ./local.app.php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - "COMPOSER_ALLOW_SUPERUSER=true"
      - "DBUS_SESSION_BUS_ADDRESS=/dev/null"
    ports:
      - 8000:8000
      - 5757:5757
    command: php artisan serve --host=0.0.0.0

  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ../docker/local.schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 13306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
